spring:
  servlet:
    multipart:
      max-file-size: 50MB

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/expense_tracker
    username: root
    password: 12345678

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true